site_name: CiviCRM Resource Management
repo_url: https://github.com/systopia/de.systopia.resource
site_description: 'A guide for the CiviCRM Resource Management extension.'
site_author: 'SYSTOPIA'
theme:
    name:
        material

nav:
    - Home: index.md

markdown_extensions:
    - attr_list
    - admonition
    - def_list
    - pymdownx.highlight:
          guess_lang: false
    - toc:
          permalink: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.mark

plugins:
    - search:
          lang: en
